# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

release:
  disable: true

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} {{ if eq .Os "windows" }}-H=windowsgui{{ end }}

archives:
  - formats: tar.gz
    name_template: >-
      {{ replace .ProjectName "-" "_" }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip

nfpms:
  - file_name_template: '{{ replace .ProjectName "-" "_" }}_{{ .Version }}_{{ .Arch }}'
    license: MIT
    maintainer: Joshua Cowie-Willox <joshwillox@gmail.com>
    homepage: https://github.com/jcwillox/system-link
    description: "A powerful bootstrapping utility for your dotfiles and system"
    bindir: /usr/bin
    formats:
      - apk
      - rpm
      - deb

dockers_v2:
  - &docker_base
    id: scratch
    images:
      - ghcr.io/jcwillox/{{ .ProjectName }}
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.url: https://github.com/jcwillox/{{ .ProjectName }}
      org.opencontainers.image.source: https://github.com/jcwillox/{{ .ProjectName }}
      org.opencontainers.image.documentation: https://github.com/jcwillox/{{ .ProjectName }}/blob/main/README.md
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: '{{ time "2006-01-02T15:04:05Z07:00" }}'
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: MIT

  - &python_base
    <<: *docker_base
    id: python3-13
    dockerfile: Dockerfile-python
    tags:
      - "{{ .Version }}-python3.13-alpine"
      - "{{ .Major }}-python3.13-alpine"
      - "{{ .Major }}.{{ .Minor }}-python3.13-alpine"
      - python3.13-alpine
    build_args:
      PYTHON_VERSION: "3.13"

  - <<: *python_base
    id: python3-14
    tags:
      - "{{ .Version }}-python3.14-alpine"
      - "{{ .Major }}-python3.14-alpine"
      - "{{ .Major }}.{{ .Minor }}-python3.14-alpine"
      - python3.14-alpine
      - python3-alpine
    build_args:
      PYTHON_VERSION: "3.14"

checksum:
  name_template: 'checksums.txt'
