ARG PYTHON_VERSION=3.14
FROM ghcr.io/astral-sh/uv:0.8.13-python${PYTHON_VERSION}-alpine

ENV SYSTEM_LINK_CONFIG=/config/config.yaml
ENV SYSTEM_LINK_LOGS_DIR=/logs

COPY system-link /usr/bin
CMD ["/usr/bin/system-link"]
