FROM scratch
ARG TARGETPLATFORM

ENV SYSTEM_LINK_CONFIG=/config/config.yaml
ENV SYSTEM_LINK_LOGS_DIR=/logs
ENV SYSTEM_LINK_LOCKS_DIR=/tmp

COPY $TARGETPLATFORM/system-link /
ENTRYPOINT ["/system-link"]
