ARG PYTHON_VERSION=3.14
FROM ghcr.io/astral-sh/uv:0.9.20-python${PYTHON_VERSION}-alpine
ARG TARGETPLATFORM

ENV SYSTEM_LINK_CONFIG=/config/config.yaml
ENV SYSTEM_LINK_LOGS_DIR=/logs

COPY $TARGETPLATFORM/system-link /usr/bin
CMD ["/usr/bin/system-link"]
